version: '3.8'

services:
  # Frontend - Next.js Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - jarvis-network

  # Backend - Python FastAPI
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-jarvis-secret-key-change-in-production}
      - DEBUG=true
    volumes:
      - ./backend:/app
      - jarvis-data:/app/data
    networks:
      - jarvis-network
    restart: unless-stopped

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - jarvis-network
    restart: unless-stopped

  # Optional: Tor proxy for deep web access
  tor:
    image: dperson/torproxy
    ports:
      - "9050:9050"
      - "9051:9051"
    environment:
      - TOR_NewCircuitPeriod=60
      - TOR_MaxCircuitDirtiness=300
    networks:
      - jarvis-network
    restart: unless-stopped

networks:
  jarvis-network:
    driver: bridge

volumes:
  jarvis-data:
    driver: local
  redis-data:
    driver: local
